/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLevel = { 'lightlyActive' : null } |
  { 'extraActive' : null } |
  { 'veryActive' : null } |
  { 'moderatelyActive' : null } |
  { 'sedentary' : null };
export type Calories = bigint;
export interface Cell { 'value' : Value, 'name' : string }
export type Code = string;
export type CodeTtl = bigint;
export interface DailySummary {
  'bmr' : Calories,
  'stepCalories' : Calories,
  'date' : Date,
  'exerciseCalories' : Calories,
  'macroBreakdown' : MacroBreakdown,
  'caloriesOut' : Calories,
  'steps' : bigint,
  'netBalance' : bigint,
  'caloriesIn' : Calories,
}
export type Date = string;
export type Email = string;
export type Error = { 'internal' : string } |
  { 'invalidInput' : string } |
  { 'notFound' : null } |
  { 'rateLimited' : null } |
  { 'unauthorized' : null };
export type Error__1 = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type EstimateResult = {
    'ok' : { 'calories' : Calories, 'macros' : MacroBreakdown }
  } |
  { 'err' : Error };
export type EstimateResult__1 = { 'ok' : { 'caloriesBurned' : Calories } } |
  { 'err' : Error };
export interface Exercise {
  'id' : bigint,
  'userId' : UserId,
  'date' : Date,
  'distance' : [] | [bigint],
  'exerciseType' : string,
  'photo' : [] | [Uint8Array],
  'caloriesBurned' : Calories,
  'durationMin' : bigint,
  'loggedAt' : Timestamp,
  'intensity' : [] | [Intensity],
}
export interface ExerciseInput {
  'date' : Date,
  'distance' : [] | [bigint],
  'exerciseType' : string,
  'photo' : [] | [Uint8Array],
  'durationMin' : bigint,
  'intensity' : [] | [Intensity],
}
export type Goal = { 'gain' : null } |
  { 'lose' : null } |
  { 'maintain' : null };
export type Intensity = { 'light' : null } |
  { 'vigorous' : null } |
  { 'moderate' : null };
export interface MacroBreakdown {
  'fat' : bigint,
  'carbs' : bigint,
  'protein' : bigint,
}
export interface Meal {
  'id' : bigint,
  'userId' : UserId,
  'date' : Date,
  'calories' : Calories,
  'description' : string,
  'portionSize' : [] | [string],
  'macros' : MacroBreakdown,
  'photo' : [] | [Uint8Array],
  'loggedAt' : Timestamp,
  'mealType' : MealType,
}
export interface MealInput {
  'date' : Date,
  'description' : string,
  'portionSize' : [] | [string],
  'photo' : [] | [Uint8Array],
  'mealType' : MealType,
}
export type MealType = { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'snack' : null } |
  { 'dinner' : null };
export interface NetBalancePoint { 'date' : Date, 'netBalance' : bigint }
export interface Profile {
  'age' : bigint,
  'bmr' : bigint,
  'sex' : Sex,
  'weight' : bigint,
  'height' : bigint,
  'activityLevel' : ActivityLevel,
  'goal' : Goal,
}
export type RequestCodeError = { 'invalidEmail' : null } |
  { 'sendFailed' : string } |
  { 'rateLimited' : null };
export type RequestCodeResult = { 'ok' : null } |
  { 'err' : RequestCodeError };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error__1 };
export type SessionToken = string;
export type SessionTtl = bigint;
export type Sex = { 'female' : null } |
  { 'male' : null };
export interface StepEntry {
  'userId' : UserId,
  'date' : Date,
  'calories' : Calories,
  'updatedAt' : Timestamp,
  'steps' : bigint,
}
export type Timestamp = bigint;
export interface User {
  'lastLoginAt' : Timestamp,
  'createdAt' : Timestamp,
  'email' : Email,
}
export type UserId = string;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VerifyCodeError = { 'wrongCode' : null } |
  { 'noPendingCode' : null } |
  { 'expired' : null } |
  { 'tooManyAttempts' : null };
export type VerifyCodeResult = { 'ok' : SessionToken } |
  { 'err' : VerifyCodeError };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__codeTtl' : ActorMethod<[], CodeTtl>,
  '__exercises' : ActorMethod<[], any>,
  '__exercisesByUserDate' : ActorMethod<[], any>,
  '__logMealApiKey' : ActorMethod<[], any>,
  '__maxAttempts' : ActorMethod<[], bigint>,
  '__meals' : ActorMethod<[], any>,
  '__mealsByUserDate' : ActorMethod<[], any>,
  '__nextExerciseId' : ActorMethod<[], any>,
  '__nextMealId' : ActorMethod<[], any>,
  '__pendingCodes' : ActorMethod<[], any>,
  '__profiles' : ActorMethod<[], any>,
  '__sessionTtl' : ActorMethod<[], SessionTtl>,
  '__sessions' : ActorMethod<[], any>,
  '__stepsByUserDate' : ActorMethod<[], any>,
  '__users' : ActorMethod<[], any>,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addExercise' : ActorMethod<
    [SessionToken, UserId, ExerciseInput, Calories],
    Exercise
  >,
  'addMeal' : ActorMethod<
    [SessionToken, UserId, MealInput, Calories, MacroBreakdown],
    Meal
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExercise' : ActorMethod<[SessionToken, bigint], boolean>,
  'deleteMeal' : ActorMethod<[SessionToken, bigint], boolean>,
  'estimateExercise' : ActorMethod<
    [SessionToken, UserId, ExerciseInput],
    EstimateResult__1
  >,
  'estimateMeal' : ActorMethod<
    [SessionToken, UserId, MealInput],
    EstimateResult
  >,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailySummary' : ActorMethod<[SessionToken, UserId, Date], DailySummary>,
  'getExercise' : ActorMethod<[SessionToken, bigint], [] | [Exercise]>,
  'getHistoryRange' : ActorMethod<
    [SessionToken, UserId, Date, Date],
    Array<DailySummary>
  >,
  'getMeal' : ActorMethod<[SessionToken, bigint], [] | [Meal]>,
  'getNetBalanceTrend' : ActorMethod<
    [SessionToken, UserId, bigint],
    Array<NetBalancePoint>
  >,
  'getProfile' : ActorMethod<[SessionToken, UserId], [] | [Profile]>,
  'getSteps' : ActorMethod<[SessionToken, UserId, Date], [] | [StepEntry]>,
  'getTodaySteps' : ActorMethod<[SessionToken, UserId], [] | [StepEntry]>,
  'getUser' : ActorMethod<[Email], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOnboarded' : ActorMethod<[SessionToken, UserId], boolean>,
  'listExercises' : ActorMethod<[SessionToken, UserId, Date], Array<Exercise>>,
  'listMeals' : ActorMethod<[SessionToken, UserId, Date], Array<Meal>>,
  'logout' : ActorMethod<[SessionToken], undefined>,
  'requestCode' : ActorMethod<[Email], RequestCodeResult>,
  'saveProfile' : ActorMethod<[SessionToken, UserId, Profile], Profile>,
  'schema' : ActorMethod<[], string>,
  'setLogMealApiKey' : ActorMethod<[string], undefined>,
  'setSteps' : ActorMethod<[SessionToken, UserId, Date, bigint], StepEntry>,
  'updateExercise' : ActorMethod<
    [SessionToken, bigint, ExerciseInput, Calories],
    [] | [Exercise]
  >,
  'updateMeal' : ActorMethod<
    [SessionToken, bigint, MealInput, Calories, MacroBreakdown],
    [] | [Meal]
  >,
  'validateSession' : ActorMethod<[SessionToken], [] | [Email]>,
  'verifyCode' : ActorMethod<[Email, Code], VerifyCodeResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];