/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CodeTtl = IDL.Nat;
export const SessionTtl = IDL.Nat;
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error__1 = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error__1 });
export const SessionToken = IDL.Text;
export const UserId = IDL.Text;
export const Date = IDL.Text;
export const Intensity = IDL.Variant({
  'light' : IDL.Null,
  'vigorous' : IDL.Null,
  'moderate' : IDL.Null,
});
export const ExerciseInput = IDL.Record({
  'date' : Date,
  'distance' : IDL.Opt(IDL.Nat),
  'exerciseType' : IDL.Text,
  'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'durationMin' : IDL.Nat,
  'intensity' : IDL.Opt(Intensity),
});
export const Calories = IDL.Nat;
export const Timestamp = IDL.Nat;
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'date' : Date,
  'distance' : IDL.Opt(IDL.Nat),
  'exerciseType' : IDL.Text,
  'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'caloriesBurned' : Calories,
  'durationMin' : IDL.Nat,
  'loggedAt' : Timestamp,
  'intensity' : IDL.Opt(Intensity),
});
export const MealType = IDL.Variant({
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'snack' : IDL.Null,
  'dinner' : IDL.Null,
});
export const MealInput = IDL.Record({
  'date' : Date,
  'description' : IDL.Text,
  'portionSize' : IDL.Opt(IDL.Text),
  'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'mealType' : MealType,
});
export const MacroBreakdown = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'protein' : IDL.Nat,
});
export const Meal = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'date' : Date,
  'calories' : Calories,
  'description' : IDL.Text,
  'portionSize' : IDL.Opt(IDL.Text),
  'macros' : MacroBreakdown,
  'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'loggedAt' : Timestamp,
  'mealType' : MealType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Error = IDL.Variant({
  'internal' : IDL.Text,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
  'rateLimited' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const EstimateResult__1 = IDL.Variant({
  'ok' : IDL.Record({ 'caloriesBurned' : Calories }),
  'err' : Error,
});
export const EstimateResult = IDL.Variant({
  'ok' : IDL.Record({ 'calories' : Calories, 'macros' : MacroBreakdown }),
  'err' : Error,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DailySummary = IDL.Record({
  'bmr' : Calories,
  'stepCalories' : Calories,
  'date' : Date,
  'exerciseCalories' : Calories,
  'macroBreakdown' : MacroBreakdown,
  'caloriesOut' : Calories,
  'steps' : IDL.Nat,
  'netBalance' : IDL.Int,
  'caloriesIn' : Calories,
});
export const NetBalancePoint = IDL.Record({
  'date' : Date,
  'netBalance' : IDL.Int,
});
export const Sex = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const ActivityLevel = IDL.Variant({
  'lightlyActive' : IDL.Null,
  'extraActive' : IDL.Null,
  'veryActive' : IDL.Null,
  'moderatelyActive' : IDL.Null,
  'sedentary' : IDL.Null,
});
export const Goal = IDL.Variant({
  'gain' : IDL.Null,
  'lose' : IDL.Null,
  'maintain' : IDL.Null,
});
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'bmr' : IDL.Nat,
  'sex' : Sex,
  'weight' : IDL.Nat,
  'height' : IDL.Nat,
  'activityLevel' : ActivityLevel,
  'goal' : Goal,
});
export const StepEntry = IDL.Record({
  'userId' : UserId,
  'date' : Date,
  'calories' : Calories,
  'updatedAt' : Timestamp,
  'steps' : IDL.Nat,
});
export const Email = IDL.Text;
export const User = IDL.Record({
  'lastLoginAt' : Timestamp,
  'createdAt' : Timestamp,
  'email' : Email,
});
export const RequestCodeError = IDL.Variant({
  'invalidEmail' : IDL.Null,
  'sendFailed' : IDL.Text,
  'rateLimited' : IDL.Null,
});
export const RequestCodeResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : RequestCodeError,
});
export const Code = IDL.Text;
export const VerifyCodeError = IDL.Variant({
  'wrongCode' : IDL.Null,
  'noPendingCode' : IDL.Null,
  'expired' : IDL.Null,
  'tooManyAttempts' : IDL.Null,
});
export const VerifyCodeResult = IDL.Variant({
  'ok' : SessionToken,
  'err' : VerifyCodeError,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__codeTtl' : IDL.Func([], [CodeTtl], ['query']),
  '__exercises' : IDL.Func([], [IDL.Reserved], ['query']),
  '__exercisesByUserDate' : IDL.Func([], [IDL.Reserved], ['query']),
  '__logMealApiKey' : IDL.Func([], [IDL.Reserved], ['query']),
  '__maxAttempts' : IDL.Func([], [IDL.Nat], ['query']),
  '__meals' : IDL.Func([], [IDL.Reserved], ['query']),
  '__mealsByUserDate' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextExerciseId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextMealId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__pendingCodes' : IDL.Func([], [IDL.Reserved], ['query']),
  '__profiles' : IDL.Func([], [IDL.Reserved], ['query']),
  '__sessionTtl' : IDL.Func([], [SessionTtl], ['query']),
  '__sessions' : IDL.Func([], [IDL.Reserved], ['query']),
  '__stepsByUserDate' : IDL.Func([], [IDL.Reserved], ['query']),
  '__users' : IDL.Func([], [IDL.Reserved], ['query']),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addExercise' : IDL.Func(
      [SessionToken, UserId, ExerciseInput, Calories],
      [Exercise],
      [],
    ),
  'addMeal' : IDL.Func(
      [SessionToken, UserId, MealInput, Calories, MacroBreakdown],
      [Meal],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExercise' : IDL.Func([SessionToken, IDL.Nat], [IDL.Bool], []),
  'deleteMeal' : IDL.Func([SessionToken, IDL.Nat], [IDL.Bool], []),
  'estimateExercise' : IDL.Func(
      [SessionToken, UserId, ExerciseInput],
      [EstimateResult__1],
      [],
    ),
  'estimateMeal' : IDL.Func(
      [SessionToken, UserId, MealInput],
      [EstimateResult],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailySummary' : IDL.Func(
      [SessionToken, UserId, Date],
      [DailySummary],
      ['query'],
    ),
  'getExercise' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Opt(Exercise)],
      ['query'],
    ),
  'getHistoryRange' : IDL.Func(
      [SessionToken, UserId, Date, Date],
      [IDL.Vec(DailySummary)],
      ['query'],
    ),
  'getMeal' : IDL.Func([SessionToken, IDL.Nat], [IDL.Opt(Meal)], ['query']),
  'getNetBalanceTrend' : IDL.Func(
      [SessionToken, UserId, IDL.Nat],
      [IDL.Vec(NetBalancePoint)],
      ['query'],
    ),
  'getProfile' : IDL.Func(
      [SessionToken, UserId],
      [IDL.Opt(Profile)],
      ['query'],
    ),
  'getSteps' : IDL.Func(
      [SessionToken, UserId, Date],
      [IDL.Opt(StepEntry)],
      ['query'],
    ),
  'getTodaySteps' : IDL.Func(
      [SessionToken, UserId],
      [IDL.Opt(StepEntry)],
      ['query'],
    ),
  'getUser' : IDL.Func([Email], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOnboarded' : IDL.Func([SessionToken, UserId], [IDL.Bool], ['query']),
  'listExercises' : IDL.Func(
      [SessionToken, UserId, Date],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'listMeals' : IDL.Func(
      [SessionToken, UserId, Date],
      [IDL.Vec(Meal)],
      ['query'],
    ),
  'logout' : IDL.Func([SessionToken], [], []),
  'requestCode' : IDL.Func([Email], [RequestCodeResult], []),
  'saveProfile' : IDL.Func([SessionToken, UserId, Profile], [Profile], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setLogMealApiKey' : IDL.Func([IDL.Text], [], []),
  'setSteps' : IDL.Func([SessionToken, UserId, Date, IDL.Nat], [StepEntry], []),
  'updateExercise' : IDL.Func(
      [SessionToken, IDL.Nat, ExerciseInput, Calories],
      [IDL.Opt(Exercise)],
      [],
    ),
  'updateMeal' : IDL.Func(
      [SessionToken, IDL.Nat, MealInput, Calories, MacroBreakdown],
      [IDL.Opt(Meal)],
      [],
    ),
  'validateSession' : IDL.Func([SessionToken], [IDL.Opt(Email)], ['query']),
  'verifyCode' : IDL.Func([Email, Code], [VerifyCodeResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CodeTtl = IDL.Nat;
  const SessionTtl = IDL.Nat;
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error__1 = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error__1 });
  const SessionToken = IDL.Text;
  const UserId = IDL.Text;
  const Date = IDL.Text;
  const Intensity = IDL.Variant({
    'light' : IDL.Null,
    'vigorous' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const ExerciseInput = IDL.Record({
    'date' : Date,
    'distance' : IDL.Opt(IDL.Nat),
    'exerciseType' : IDL.Text,
    'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'durationMin' : IDL.Nat,
    'intensity' : IDL.Opt(Intensity),
  });
  const Calories = IDL.Nat;
  const Timestamp = IDL.Nat;
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'date' : Date,
    'distance' : IDL.Opt(IDL.Nat),
    'exerciseType' : IDL.Text,
    'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'caloriesBurned' : Calories,
    'durationMin' : IDL.Nat,
    'loggedAt' : Timestamp,
    'intensity' : IDL.Opt(Intensity),
  });
  const MealType = IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'snack' : IDL.Null,
    'dinner' : IDL.Null,
  });
  const MealInput = IDL.Record({
    'date' : Date,
    'description' : IDL.Text,
    'portionSize' : IDL.Opt(IDL.Text),
    'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'mealType' : MealType,
  });
  const MacroBreakdown = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'protein' : IDL.Nat,
  });
  const Meal = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'date' : Date,
    'calories' : Calories,
    'description' : IDL.Text,
    'portionSize' : IDL.Opt(IDL.Text),
    'macros' : MacroBreakdown,
    'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'loggedAt' : Timestamp,
    'mealType' : MealType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Error = IDL.Variant({
    'internal' : IDL.Text,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
    'rateLimited' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const EstimateResult__1 = IDL.Variant({
    'ok' : IDL.Record({ 'caloriesBurned' : Calories }),
    'err' : Error,
  });
  const EstimateResult = IDL.Variant({
    'ok' : IDL.Record({ 'calories' : Calories, 'macros' : MacroBreakdown }),
    'err' : Error,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DailySummary = IDL.Record({
    'bmr' : Calories,
    'stepCalories' : Calories,
    'date' : Date,
    'exerciseCalories' : Calories,
    'macroBreakdown' : MacroBreakdown,
    'caloriesOut' : Calories,
    'steps' : IDL.Nat,
    'netBalance' : IDL.Int,
    'caloriesIn' : Calories,
  });
  const NetBalancePoint = IDL.Record({ 'date' : Date, 'netBalance' : IDL.Int });
  const Sex = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const ActivityLevel = IDL.Variant({
    'lightlyActive' : IDL.Null,
    'extraActive' : IDL.Null,
    'veryActive' : IDL.Null,
    'moderatelyActive' : IDL.Null,
    'sedentary' : IDL.Null,
  });
  const Goal = IDL.Variant({
    'gain' : IDL.Null,
    'lose' : IDL.Null,
    'maintain' : IDL.Null,
  });
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'bmr' : IDL.Nat,
    'sex' : Sex,
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'activityLevel' : ActivityLevel,
    'goal' : Goal,
  });
  const StepEntry = IDL.Record({
    'userId' : UserId,
    'date' : Date,
    'calories' : Calories,
    'updatedAt' : Timestamp,
    'steps' : IDL.Nat,
  });
  const Email = IDL.Text;
  const User = IDL.Record({
    'lastLoginAt' : Timestamp,
    'createdAt' : Timestamp,
    'email' : Email,
  });
  const RequestCodeError = IDL.Variant({
    'invalidEmail' : IDL.Null,
    'sendFailed' : IDL.Text,
    'rateLimited' : IDL.Null,
  });
  const RequestCodeResult = IDL.Variant({
    'ok' : IDL.Null,
    'err' : RequestCodeError,
  });
  const Code = IDL.Text;
  const VerifyCodeError = IDL.Variant({
    'wrongCode' : IDL.Null,
    'noPendingCode' : IDL.Null,
    'expired' : IDL.Null,
    'tooManyAttempts' : IDL.Null,
  });
  const VerifyCodeResult = IDL.Variant({
    'ok' : SessionToken,
    'err' : VerifyCodeError,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__codeTtl' : IDL.Func([], [CodeTtl], ['query']),
    '__exercises' : IDL.Func([], [IDL.Reserved], ['query']),
    '__exercisesByUserDate' : IDL.Func([], [IDL.Reserved], ['query']),
    '__logMealApiKey' : IDL.Func([], [IDL.Reserved], ['query']),
    '__maxAttempts' : IDL.Func([], [IDL.Nat], ['query']),
    '__meals' : IDL.Func([], [IDL.Reserved], ['query']),
    '__mealsByUserDate' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextExerciseId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextMealId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__pendingCodes' : IDL.Func([], [IDL.Reserved], ['query']),
    '__profiles' : IDL.Func([], [IDL.Reserved], ['query']),
    '__sessionTtl' : IDL.Func([], [SessionTtl], ['query']),
    '__sessions' : IDL.Func([], [IDL.Reserved], ['query']),
    '__stepsByUserDate' : IDL.Func([], [IDL.Reserved], ['query']),
    '__users' : IDL.Func([], [IDL.Reserved], ['query']),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addExercise' : IDL.Func(
        [SessionToken, UserId, ExerciseInput, Calories],
        [Exercise],
        [],
      ),
    'addMeal' : IDL.Func(
        [SessionToken, UserId, MealInput, Calories, MacroBreakdown],
        [Meal],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExercise' : IDL.Func([SessionToken, IDL.Nat], [IDL.Bool], []),
    'deleteMeal' : IDL.Func([SessionToken, IDL.Nat], [IDL.Bool], []),
    'estimateExercise' : IDL.Func(
        [SessionToken, UserId, ExerciseInput],
        [EstimateResult__1],
        [],
      ),
    'estimateMeal' : IDL.Func(
        [SessionToken, UserId, MealInput],
        [EstimateResult],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailySummary' : IDL.Func(
        [SessionToken, UserId, Date],
        [DailySummary],
        ['query'],
      ),
    'getExercise' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Opt(Exercise)],
        ['query'],
      ),
    'getHistoryRange' : IDL.Func(
        [SessionToken, UserId, Date, Date],
        [IDL.Vec(DailySummary)],
        ['query'],
      ),
    'getMeal' : IDL.Func([SessionToken, IDL.Nat], [IDL.Opt(Meal)], ['query']),
    'getNetBalanceTrend' : IDL.Func(
        [SessionToken, UserId, IDL.Nat],
        [IDL.Vec(NetBalancePoint)],
        ['query'],
      ),
    'getProfile' : IDL.Func(
        [SessionToken, UserId],
        [IDL.Opt(Profile)],
        ['query'],
      ),
    'getSteps' : IDL.Func(
        [SessionToken, UserId, Date],
        [IDL.Opt(StepEntry)],
        ['query'],
      ),
    'getTodaySteps' : IDL.Func(
        [SessionToken, UserId],
        [IDL.Opt(StepEntry)],
        ['query'],
      ),
    'getUser' : IDL.Func([Email], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOnboarded' : IDL.Func([SessionToken, UserId], [IDL.Bool], ['query']),
    'listExercises' : IDL.Func(
        [SessionToken, UserId, Date],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'listMeals' : IDL.Func(
        [SessionToken, UserId, Date],
        [IDL.Vec(Meal)],
        ['query'],
      ),
    'logout' : IDL.Func([SessionToken], [], []),
    'requestCode' : IDL.Func([Email], [RequestCodeResult], []),
    'saveProfile' : IDL.Func([SessionToken, UserId, Profile], [Profile], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setLogMealApiKey' : IDL.Func([IDL.Text], [], []),
    'setSteps' : IDL.Func(
        [SessionToken, UserId, Date, IDL.Nat],
        [StepEntry],
        [],
      ),
    'updateExercise' : IDL.Func(
        [SessionToken, IDL.Nat, ExerciseInput, Calories],
        [IDL.Opt(Exercise)],
        [],
      ),
    'updateMeal' : IDL.Func(
        [SessionToken, IDL.Nat, MealInput, Calories, MacroBreakdown],
        [IDL.Opt(Meal)],
        [],
      ),
    'validateSession' : IDL.Func([SessionToken], [IDL.Opt(Email)], ['query']),
    'verifyCode' : IDL.Func([Email, Code], [VerifyCodeResult], []),
  });
};

export const init = ({ IDL }) => { return []; };