/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Timestamp = bigint;
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error__1;
};
export interface Profile {
    age: bigint;
    bmr: bigint;
    sex: Sex;
    weight: bigint;
    height: bigint;
    activityLevel: ActivityLevel;
    goal: Goal;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type RequestCodeResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: RequestCodeError;
};
export type EstimateResult = {
    __kind__: "ok";
    ok: {
        calories: Calories;
        macros: MacroBreakdown;
    };
} | {
    __kind__: "err";
    err: Error_;
};
export type Calories = bigint;
export type Code = string;
export type SessionToken = string;
export interface Cell {
    value: Value;
    name: string;
}
export interface StepEntry {
    userId: UserId;
    date: Date_;
    calories: Calories;
    updatedAt: Timestamp;
    steps: bigint;
}
export type VerifyCodeResult = {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: VerifyCodeError;
};
export type RequestCodeError = {
    __kind__: "invalidEmail";
    invalidEmail: null;
} | {
    __kind__: "sendFailed";
    sendFailed: string;
} | {
    __kind__: "rateLimited";
    rateLimited: null;
};
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export type CodeTtl = bigint;
export type Email = string;
export interface NetBalancePoint {
    date: Date_;
    netBalance: bigint;
}
export interface Meal {
    id: bigint;
    userId: UserId;
    date: Date_;
    calories: Calories;
    description: string;
    portionSize?: string;
    macros: MacroBreakdown;
    photo?: Uint8Array;
    loggedAt: Timestamp;
    mealType: MealType;
}
export interface Exercise {
    id: bigint;
    userId: UserId;
    date: Date_;
    distance?: bigint;
    exerciseType: string;
    photo?: Uint8Array;
    caloriesBurned: Calories;
    durationMin: bigint;
    loggedAt: Timestamp;
    intensity?: Intensity;
}
export type Date_ = string;
export interface User {
    lastLoginAt: Timestamp;
    createdAt: Timestamp;
    email: Email;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type Error__1 = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Error_ = {
    __kind__: "internal";
    internal: string;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "rateLimited";
    rateLimited: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export interface DailySummary {
    bmr: Calories;
    stepCalories: Calories;
    date: Date_;
    exerciseCalories: Calories;
    macroBreakdown: MacroBreakdown;
    caloriesOut: Calories;
    steps: bigint;
    netBalance: bigint;
    caloriesIn: Calories;
}
export type UserId = string;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface ExerciseInput {
    date: Date_;
    distance?: bigint;
    exerciseType: string;
    photo?: Uint8Array;
    durationMin: bigint;
    intensity?: Intensity;
}
export interface MealInput {
    date: Date_;
    description: string;
    portionSize?: string;
    photo?: Uint8Array;
    mealType: MealType;
}
export type SessionTtl = bigint;
export interface MacroBreakdown {
    fat: bigint;
    carbs: bigint;
    protein: bigint;
}
export type EstimateResult__1 = {
    __kind__: "ok";
    ok: {
        caloriesBurned: Calories;
    };
} | {
    __kind__: "err";
    err: Error_;
};
export enum ActivityLevel {
    lightlyActive = "lightlyActive",
    extraActive = "extraActive",
    veryActive = "veryActive",
    moderatelyActive = "moderatelyActive",
    sedentary = "sedentary"
}
export enum Goal {
    gain = "gain",
    lose = "lose",
    maintain = "maintain"
}
export enum Intensity {
    light = "light",
    vigorous = "vigorous",
    moderate = "moderate"
}
export enum MealType {
    breakfast = "breakfast",
    lunch = "lunch",
    snack = "snack",
    dinner = "dinner"
}
export enum Sex {
    female = "female",
    male = "male"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VerifyCodeError {
    wrongCode = "wrongCode",
    noPendingCode = "noPendingCode",
    expired = "expired",
    tooManyAttempts = "tooManyAttempts"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __codeTtl(): Promise<CodeTtl>;
    __exercises(): Promise<any>;
    __exercisesByUserDate(): Promise<any>;
    __logMealApiKey(): Promise<any>;
    __maxAttempts(): Promise<bigint>;
    __meals(): Promise<any>;
    __mealsByUserDate(): Promise<any>;
    __nextExerciseId(): Promise<any>;
    __nextMealId(): Promise<any>;
    __pendingCodes(): Promise<any>;
    __profiles(): Promise<any>;
    __sessionTtl(): Promise<SessionTtl>;
    __sessions(): Promise<any>;
    __stepsByUserDate(): Promise<any>;
    __users(): Promise<any>;
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addExercise(sessionToken: SessionToken, userId: UserId, input: ExerciseInput, caloriesBurned: Calories): Promise<Exercise>;
    addMeal(sessionToken: SessionToken, userId: UserId, input: MealInput, calories: Calories, macros: MacroBreakdown): Promise<Meal>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteExercise(sessionToken: SessionToken, exerciseId: bigint): Promise<boolean>;
    deleteMeal(sessionToken: SessionToken, mealId: bigint): Promise<boolean>;
    estimateExercise(sessionToken: SessionToken, userId: UserId, input: ExerciseInput): Promise<EstimateResult__1>;
    estimateMeal(sessionToken: SessionToken, userId: UserId, input: MealInput): Promise<EstimateResult>;
    execute(qJson: string): Promise<Result>;
    getCallerUserRole(): Promise<UserRole>;
    getDailySummary(sessionToken: SessionToken, userId: UserId, date: Date_): Promise<DailySummary>;
    getExercise(sessionToken: SessionToken, exerciseId: bigint): Promise<Exercise | null>;
    getHistoryRange(sessionToken: SessionToken, userId: UserId, startDate: Date_, endDate: Date_): Promise<Array<DailySummary>>;
    getMeal(sessionToken: SessionToken, mealId: bigint): Promise<Meal | null>;
    getNetBalanceTrend(sessionToken: SessionToken, userId: UserId, days: bigint): Promise<Array<NetBalancePoint>>;
    getProfile(sessionToken: SessionToken, userId: UserId): Promise<Profile | null>;
    getSteps(sessionToken: SessionToken, userId: UserId, date: Date_): Promise<StepEntry | null>;
    getTodaySteps(sessionToken: SessionToken, userId: UserId): Promise<StepEntry | null>;
    getUser(email: Email): Promise<User | null>;
    isCallerAdmin(): Promise<boolean>;
    isOnboarded(sessionToken: SessionToken, userId: UserId): Promise<boolean>;
    listExercises(sessionToken: SessionToken, userId: UserId, date: Date_): Promise<Array<Exercise>>;
    listMeals(sessionToken: SessionToken, userId: UserId, date: Date_): Promise<Array<Meal>>;
    logout(token: SessionToken): Promise<void>;
    requestCode(email: Email): Promise<RequestCodeResult>;
    saveProfile(sessionToken: SessionToken, userId: UserId, profile: Profile): Promise<Profile>;
    schema(): Promise<string>;
    setLogMealApiKey(key: string): Promise<void>;
    setSteps(sessionToken: SessionToken, userId: UserId, date: Date_, stepCount: bigint): Promise<StepEntry>;
    updateExercise(sessionToken: SessionToken, exerciseId: bigint, input: ExerciseInput, caloriesBurned: Calories): Promise<Exercise | null>;
    updateMeal(sessionToken: SessionToken, mealId: bigint, input: MealInput, calories: Calories, macros: MacroBreakdown): Promise<Meal | null>;
    validateSession(token: SessionToken): Promise<Email | null>;
    verifyCode(email: Email, code: Code): Promise<VerifyCodeResult>;
}
import type { ActivityLevel as _ActivityLevel, Calories as _Calories, Cell as _Cell, Date as _Date, Email as _Email, Error as _Error, Error__1 as _Error__1, EstimateResult as _EstimateResult, EstimateResult__1 as _EstimateResult__1, Exercise as _Exercise, ExerciseInput as _ExerciseInput, Goal as _Goal, Intensity as _Intensity, MacroBreakdown as _MacroBreakdown, Meal as _Meal, MealInput as _MealInput, MealType as _MealType, Profile as _Profile, RequestCodeError as _RequestCodeError, RequestCodeResult as _RequestCodeResult, Result as _Result, Result__1 as _Result__1, SessionToken as _SessionToken, Sex as _Sex, StepEntry as _StepEntry, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserRole as _UserRole, Value as _Value, VerifyCodeError as _VerifyCodeError, VerifyCodeResult as _VerifyCodeResult, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __codeTtl(): Promise<CodeTtl> {
        if (this.processError) {
            try {
                const result = await this.actor.__codeTtl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__codeTtl();
            return result;
        }
    }
    async __exercises(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__exercises();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__exercises();
            return result;
        }
    }
    async __exercisesByUserDate(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__exercisesByUserDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__exercisesByUserDate();
            return result;
        }
    }
    async __logMealApiKey(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__logMealApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__logMealApiKey();
            return result;
        }
    }
    async __maxAttempts(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__maxAttempts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__maxAttempts();
            return result;
        }
    }
    async __meals(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__meals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__meals();
            return result;
        }
    }
    async __mealsByUserDate(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__mealsByUserDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__mealsByUserDate();
            return result;
        }
    }
    async __nextExerciseId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextExerciseId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextExerciseId();
            return result;
        }
    }
    async __nextMealId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextMealId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextMealId();
            return result;
        }
    }
    async __pendingCodes(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__pendingCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__pendingCodes();
            return result;
        }
    }
    async __profiles(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__profiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__profiles();
            return result;
        }
    }
    async __sessionTtl(): Promise<SessionTtl> {
        if (this.processError) {
            try {
                const result = await this.actor.__sessionTtl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__sessionTtl();
            return result;
        }
    }
    async __sessions(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__sessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__sessions();
            return result;
        }
    }
    async __stepsByUserDate(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__stepsByUserDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__stepsByUserDate();
            return result;
        }
    }
    async __users(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__users();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__users();
            return result;
        }
    }
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addExercise(arg0: SessionToken, arg1: UserId, arg2: ExerciseInput, arg3: Calories): Promise<Exercise> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercise(arg0, arg1, to_candid_ExerciseInput_n12(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Exercise_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercise(arg0, arg1, to_candid_ExerciseInput_n12(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Exercise_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async addMeal(arg0: SessionToken, arg1: UserId, arg2: MealInput, arg3: Calories, arg4: MacroBreakdown): Promise<Meal> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeal(arg0, arg1, to_candid_MealInput_n22(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_Meal_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeal(arg0, arg1, to_candid_MealInput_n22(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_Meal_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteExercise(arg0: SessionToken, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExercise(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExercise(arg0, arg1);
            return result;
        }
    }
    async deleteMeal(arg0: SessionToken, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeal(arg0, arg1);
            return result;
        }
    }
    async estimateExercise(arg0: SessionToken, arg1: UserId, arg2: ExerciseInput): Promise<EstimateResult__1> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateExercise(arg0, arg1, to_candid_ExerciseInput_n12(this._uploadFile, this._downloadFile, arg2));
                return from_candid_EstimateResult__1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateExercise(arg0, arg1, to_candid_ExerciseInput_n12(this._uploadFile, this._downloadFile, arg2));
            return from_candid_EstimateResult__1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async estimateMeal(arg0: SessionToken, arg1: UserId, arg2: MealInput): Promise<EstimateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateMeal(arg0, arg1, to_candid_MealInput_n22(this._uploadFile, this._downloadFile, arg2));
                return from_candid_EstimateResult_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateMeal(arg0, arg1, to_candid_MealInput_n22(this._uploadFile, this._downloadFile, arg2));
            return from_candid_EstimateResult_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailySummary(arg0: SessionToken, arg1: UserId, arg2: Date_): Promise<DailySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySummary(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySummary(arg0, arg1, arg2);
            return result;
        }
    }
    async getExercise(arg0: SessionToken, arg1: bigint): Promise<Exercise | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercise(arg0, arg1);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercise(arg0, arg1);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistoryRange(arg0: SessionToken, arg1: UserId, arg2: Date_, arg3: Date_): Promise<Array<DailySummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoryRange(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoryRange(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getMeal(arg0: SessionToken, arg1: bigint): Promise<Meal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeal(arg0, arg1);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeal(arg0, arg1);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNetBalanceTrend(arg0: SessionToken, arg1: UserId, arg2: bigint): Promise<Array<NetBalancePoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNetBalanceTrend(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNetBalanceTrend(arg0, arg1, arg2);
            return result;
        }
    }
    async getProfile(arg0: SessionToken, arg1: UserId): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0, arg1);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0, arg1);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSteps(arg0: SessionToken, arg1: UserId, arg2: Date_): Promise<StepEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSteps(arg0, arg1, arg2);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSteps(arg0, arg1, arg2);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaySteps(arg0: SessionToken, arg1: UserId): Promise<StepEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaySteps(arg0, arg1);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaySteps(arg0, arg1);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: Email): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOnboarded(arg0: SessionToken, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOnboarded(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOnboarded(arg0, arg1);
            return result;
        }
    }
    async listExercises(arg0: SessionToken, arg1: UserId, arg2: Date_): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExercises(arg0, arg1, arg2);
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExercises(arg0, arg1, arg2);
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMeals(arg0: SessionToken, arg1: UserId, arg2: Date_): Promise<Array<Meal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMeals(arg0, arg1, arg2);
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMeals(arg0, arg1, arg2);
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async requestCode(arg0: Email): Promise<RequestCodeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.requestCode(arg0);
                return from_candid_RequestCodeResult_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestCode(arg0);
            return from_candid_RequestCodeResult_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveProfile(arg0: SessionToken, arg1: UserId, arg2: Profile): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0, arg1, to_candid_Profile_n68(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Profile_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0, arg1, to_candid_Profile_n68(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Profile_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setLogMealApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLogMealApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLogMealApiKey(arg0);
            return result;
        }
    }
    async setSteps(arg0: SessionToken, arg1: UserId, arg2: Date_, arg3: bigint): Promise<StepEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.setSteps(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSteps(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateExercise(arg0: SessionToken, arg1: bigint, arg2: ExerciseInput, arg3: Calories): Promise<Exercise | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExercise(arg0, arg1, to_candid_ExerciseInput_n12(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExercise(arg0, arg1, to_candid_ExerciseInput_n12(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMeal(arg0: SessionToken, arg1: bigint, arg2: MealInput, arg3: Calories, arg4: MacroBreakdown): Promise<Meal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMeal(arg0, arg1, to_candid_MealInput_n22(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMeal(arg0, arg1, to_candid_MealInput_n22(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateSession(arg0: SessionToken): Promise<Email | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyCode(arg0: Email, arg1: Code): Promise<VerifyCodeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyCode(arg0, arg1);
                return from_candid_VerifyCodeResult_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyCode(arg0, arg1);
            return from_candid_VerifyCodeResult_n77(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityLevel_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLevel): ActivityLevel {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Error__1_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error__1): Error__1 {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_EstimateResult__1_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EstimateResult__1): EstimateResult__1 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_EstimateResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EstimateResult): EstimateResult {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Intensity_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Intensity): Intensity {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_MealType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealType): MealType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Meal_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Meal): Meal {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_RequestCodeError_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestCodeError): RequestCodeError {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_RequestCodeResult_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestCodeResult): RequestCodeResult {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Sex_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sex): Sex {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_VerifyCodeError_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifyCodeError): VerifyCodeError {
    return from_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function from_candid_VerifyCodeResult_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifyCodeResult): VerifyCodeResult {
    return from_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Intensity]): Intensity | null {
    return value.length === 0 ? null : from_candid_Intensity_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Exercise]): Exercise | null {
    return value.length === 0 ? null : from_candid_Exercise_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Meal]): Meal | null {
    return value.length === 0 ? null : from_candid_Meal_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StepEntry]): StepEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Email]): Email | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: _UserId;
    date: _Date;
    distance: [] | [bigint];
    exerciseType: string;
    photo: [] | [Uint8Array];
    caloriesBurned: _Calories;
    durationMin: bigint;
    loggedAt: _Timestamp;
    intensity: [] | [_Intensity];
}): {
    id: bigint;
    userId: UserId;
    date: Date_;
    distance?: bigint;
    exerciseType: string;
    photo?: Uint8Array;
    caloriesBurned: Calories;
    durationMin: bigint;
    loggedAt: Timestamp;
    intensity?: Intensity;
} {
    return {
        id: value.id,
        userId: value.userId,
        date: value.date,
        distance: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.distance)),
        exerciseType: value.exerciseType,
        photo: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.photo)),
        caloriesBurned: value.caloriesBurned,
        durationMin: value.durationMin,
        loggedAt: value.loggedAt,
        intensity: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.intensity))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: _UserId;
    date: _Date;
    calories: _Calories;
    description: string;
    portionSize: [] | [string];
    macros: _MacroBreakdown;
    photo: [] | [Uint8Array];
    loggedAt: _Timestamp;
    mealType: _MealType;
}): {
    id: bigint;
    userId: UserId;
    date: Date_;
    calories: Calories;
    description: string;
    portionSize?: string;
    macros: MacroBreakdown;
    photo?: Uint8Array;
    loggedAt: Timestamp;
    mealType: MealType;
} {
    return {
        id: value.id,
        userId: value.userId,
        date: value.date,
        calories: value.calories,
        description: value.description,
        portionSize: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.portionSize)),
        macros: value.macros,
        photo: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.photo)),
        loggedAt: value.loggedAt,
        mealType: from_candid_MealType_n29(_uploadFile, _downloadFile, value.mealType)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n41(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n45(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bmr: bigint;
    sex: _Sex;
    weight: bigint;
    height: bigint;
    activityLevel: _ActivityLevel;
    goal: _Goal;
}): {
    age: bigint;
    bmr: bigint;
    sex: Sex;
    weight: bigint;
    height: bigint;
    activityLevel: ActivityLevel;
    goal: Goal;
} {
    return {
        age: value.age,
        bmr: value.bmr,
        sex: from_candid_Sex_n54(_uploadFile, _downloadFile, value.sex),
        weight: value.weight,
        height: value.height,
        activityLevel: from_candid_ActivityLevel_n56(_uploadFile, _downloadFile, value.activityLevel),
        goal: from_candid_Goal_n58(_uploadFile, _downloadFile, value.goal)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    light: null;
} | {
    vigorous: null;
} | {
    moderate: null;
}): Intensity {
    return "light" in value ? Intensity.light : "vigorous" in value ? Intensity.vigorous : "moderate" in value ? Intensity.moderate : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
}): MealType {
    return "breakfast" in value ? MealType.breakfast : "lunch" in value ? MealType.lunch : "snack" in value ? MealType.snack : "dinner" in value ? MealType.dinner : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        caloriesBurned: _Calories;
    };
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: {
        caloriesBurned: Calories;
    };
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n35(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internal: string;
} | {
    invalidInput: string;
} | {
    notFound: null;
} | {
    rateLimited: null;
} | {
    unauthorized: null;
}): {
    __kind__: "internal";
    internal: string;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "rateLimited";
    rateLimited: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "internal" in value ? {
        __kind__: "internal",
        internal: value.internal
    } : "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "rateLimited" in value ? {
        __kind__: "rateLimited",
        rateLimited: value.rateLimited
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        calories: _Calories;
        macros: _MacroBreakdown;
    };
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: {
        calories: Calories;
        macros: MacroBreakdown;
    };
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n35(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Sex {
    return "female" in value ? Sex.female : "male" in value ? Sex.male : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lightlyActive: null;
} | {
    extraActive: null;
} | {
    veryActive: null;
} | {
    moderatelyActive: null;
} | {
    sedentary: null;
}): ActivityLevel {
    return "lightlyActive" in value ? ActivityLevel.lightlyActive : "extraActive" in value ? ActivityLevel.extraActive : "veryActive" in value ? ActivityLevel.veryActive : "moderatelyActive" in value ? ActivityLevel.moderatelyActive : "sedentary" in value ? ActivityLevel.sedentary : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gain: null;
} | {
    lose: null;
} | {
    maintain: null;
}): Goal {
    return "gain" in value ? Goal.gain : "lose" in value ? Goal.lose : "maintain" in value ? Goal.maintain : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _RequestCodeError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: RequestCodeError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_RequestCodeError_n66(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidEmail: null;
} | {
    sendFailed: string;
} | {
    rateLimited: null;
}): {
    __kind__: "invalidEmail";
    invalidEmail: null;
} | {
    __kind__: "sendFailed";
    sendFailed: string;
} | {
    __kind__: "rateLimited";
    rateLimited: null;
} {
    return "invalidEmail" in value ? {
        __kind__: "invalidEmail",
        invalidEmail: value.invalidEmail
    } : "sendFailed" in value ? {
        __kind__: "sendFailed",
        sendFailed: value.sendFailed
    } : "rateLimited" in value ? {
        __kind__: "rateLimited",
        rateLimited: value.rateLimited
    } : value;
}
function from_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionToken;
} | {
    err: _VerifyCodeError;
}): {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: VerifyCodeError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_VerifyCodeError_n79(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wrongCode: null;
} | {
    noPendingCode: null;
} | {
    expired: null;
} | {
    tooManyAttempts: null;
}): VerifyCodeError {
    return "wrongCode" in value ? VerifyCodeError.wrongCode : "noPendingCode" in value ? VerifyCodeError.noPendingCode : "expired" in value ? VerifyCodeError.expired : "tooManyAttempts" in value ? VerifyCodeError.tooManyAttempts : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error__1;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error__1;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error__1_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Meal>): Array<Meal> {
    return value.map((x)=>from_candid_Meal_n26(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityLevel_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): _ActivityLevel {
    return to_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function to_candid_ExerciseInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExerciseInput): _ExerciseInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function to_candid_Intensity_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Intensity): _Intensity {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_MealInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealInput): _MealInput {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_MealType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealType): _MealType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_Sex_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sex): _Sex {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Date_;
    distance?: bigint;
    exerciseType: string;
    photo?: Uint8Array;
    durationMin: bigint;
    intensity?: Intensity;
}): {
    date: _Date;
    distance: [] | [bigint];
    exerciseType: string;
    photo: [] | [Uint8Array];
    durationMin: bigint;
    intensity: [] | [_Intensity];
} {
    return {
        date: value.date,
        distance: value.distance ? candid_some(value.distance) : candid_none(),
        exerciseType: value.exerciseType,
        photo: value.photo ? candid_some(value.photo) : candid_none(),
        durationMin: value.durationMin,
        intensity: value.intensity ? candid_some(to_candid_Intensity_n14(_uploadFile, _downloadFile, value.intensity)) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Date_;
    description: string;
    portionSize?: string;
    photo?: Uint8Array;
    mealType: MealType;
}): {
    date: _Date;
    description: string;
    portionSize: [] | [string];
    photo: [] | [Uint8Array];
    mealType: _MealType;
} {
    return {
        date: value.date,
        description: value.description,
        portionSize: value.portionSize ? candid_some(value.portionSize) : candid_none(),
        photo: value.photo ? candid_some(value.photo) : candid_none(),
        mealType: to_candid_MealType_n24(_uploadFile, _downloadFile, value.mealType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bmr: bigint;
    sex: Sex;
    weight: bigint;
    height: bigint;
    activityLevel: ActivityLevel;
    goal: Goal;
}): {
    age: bigint;
    bmr: bigint;
    sex: _Sex;
    weight: bigint;
    height: bigint;
    activityLevel: _ActivityLevel;
    goal: _Goal;
} {
    return {
        age: value.age,
        bmr: value.bmr,
        sex: to_candid_Sex_n70(_uploadFile, _downloadFile, value.sex),
        weight: value.weight,
        height: value.height,
        activityLevel: to_candid_ActivityLevel_n72(_uploadFile, _downloadFile, value.activityLevel),
        goal: to_candid_Goal_n74(_uploadFile, _downloadFile, value.goal)
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Intensity): {
    light: null;
} | {
    vigorous: null;
} | {
    moderate: null;
} {
    return value == Intensity.light ? {
        light: null
    } : value == Intensity.vigorous ? {
        vigorous: null
    } : value == Intensity.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealType): {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
} {
    return value == MealType.breakfast ? {
        breakfast: null
    } : value == MealType.lunch ? {
        lunch: null
    } : value == MealType.snack ? {
        snack: null
    } : value == MealType.dinner ? {
        dinner: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sex): {
    female: null;
} | {
    male: null;
} {
    return value == Sex.female ? {
        female: null
    } : value == Sex.male ? {
        male: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): {
    lightlyActive: null;
} | {
    extraActive: null;
} | {
    veryActive: null;
} | {
    moderatelyActive: null;
} | {
    sedentary: null;
} {
    return value == ActivityLevel.lightlyActive ? {
        lightlyActive: null
    } : value == ActivityLevel.extraActive ? {
        extraActive: null
    } : value == ActivityLevel.veryActive ? {
        veryActive: null
    } : value == ActivityLevel.moderatelyActive ? {
        moderatelyActive: null
    } : value == ActivityLevel.sedentary ? {
        sedentary: null
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    gain: null;
} | {
    lose: null;
} | {
    maintain: null;
} {
    return value == Goal.gain ? {
        gain: null
    } : value == Goal.lose ? {
        lose: null
    } : value == Goal.maintain ? {
        maintain: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
